---
- name: Install lets encrypt
  hosts: monitor
  become: true
  gather_facts: false
  pre_tasks:
    - name: update and upgrade
      apt:
        upgrade: dist
        update_cache: true
  roles:
    - lets_encrypt
