---
- name: Set up a monitor
  hosts: monitor
  become: true
  gather_facts: false
  roles:
    - prepare
    - nginx
    - node_exporter
    - prometheus
    - grafana
    - alert_manager
    - loki
    - promtail
